"""Generator identity and source hashing for generated artifacts."""

from __future__ import annotations

import hashlib
import json

from .models import LtpModel, to_dict

GENERATOR = "ltp 0.1.0"

MARKDOWN_HEADER = (
    "<!-- Generated by ltp. Do not edit this file; edit ltp/ltp-model.yaml and run "
    "`ltp sync`. -->\n\n"
)
MERMAID_HEADER = (
    "%% Generated by ltp. Do not edit; edit ltp/ltp-model.yaml and run `ltp sync`.\n"
)


def source_hash(model: LtpModel) -> str:
    """A stable sha256 of the whole model. Identical models hash identically,
    regardless of which defaults were written out in the YAML."""
    canonical = json.dumps(
        to_dict(model, prune=False),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()
